name: flutter_game_challenge
description: A project for the Flutter game challenge.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.16.7"

dependencies:
  audioplayers: ^5.2.0
  bezier: ^1.2.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flame:  ^1.14.0
  flame_audio: ^2.1.3
  flame_behaviors: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  google_fonts: ^6.0.0
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  vector_math: ^2.1.4

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  flame_test: ^1.14.0
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.5.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
    - assets/images/catcher/boxes/
    - assets/images/catcher/bg/bg.png
    - assets/images/catcher/drops/glass/
    - assets/images/catcher/drops/organic/
    - assets/images/catcher/drops/plastic/
    - assets/images/catcher/drops/electric/
    - assets/images/catcher/drops/paper/
    - assets/images/catcher/animations/
    - assets/images/catcher/tutorial/
    - assets/images/catcher/button/

  fonts:
    - family: Mplus
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf

flutter_gen:
  output: lib/common/assets/

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    enabled: true
    outputs:
      class_name: FlutterGameChallengeColors
    inputs:
      - assets/colors/colors.xml
