name: recyclo
version: 1.0.0
publish_to: none
description: A recycling game showing how waste sorting leads to useful products through recycling. Make a difference!
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.19.2'
dependencies:
  audioplayers: ^5.2.1
  bezier: ^1.2.0
  bloc: ^8.1.2
  cloud_functions: ^4.6.6
  collection: ^1.18.0
  device_info_plus: ^8.2.0
  equatable: ^2.0.5
  firebase_core: ^2.25.5
  flame: ^1.14.0
  flame_audio: ^2.1.3
  flame_behaviors: ^1.0.0
  flame_forge2d: ^0.16.0+5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.0
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  uuid: ^4.3.3
  vector_math: ^2.1.4
  video_player: ^2.8.2

dependency_overrides:
  video_player_avfoundation:
    git:
      url: https://github.com/DenisovAV/flutter-tvos-packages.git
      path: packages/video_player/video_player_avfoundation
  shared_preferences_foundation:
    git:
      url: https://github.com/DenisovAV/flutter-tvos-packages.git
      path: packages/shared_preferences/shared_preferences_foundation
  video_player_platform_interface:
    git:
      url: https://github.com/DenisovAV/flutter-tvos-packages.git
      path: packages/video_player/video_player_platform_interface
  shared_preferences_platform_interface:
    git:
      url: https://github.com/DenisovAV/flutter-tvos-packages.git
      path: packages/shared_preferences/shared_preferences_platform_interface

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  flame_test: ^1.14.0
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.5.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/licenses/poppins/
    - assets/images/catcher/boxes/
    - assets/images/catcher/bg/
    - assets/images/catcher/drops/glass/
    - assets/images/catcher/drops/organic/
    - assets/images/catcher/drops/plastic/
    - assets/images/catcher/drops/electric/
    - assets/images/catcher/drops/paper/
    - assets/images/catcher/animations/
    - assets/images/catcher/tutorial/
    - assets/images/catcher/button/
    - assets/images/clicker/images/
    - assets/audio/

  fonts:
    - family: Sniglet
      fonts:
        - asset: assets/fonts/Sniglet-Regular.ttf

flutter_gen:
  output: lib/common/assets/

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    enabled: true
    outputs:
      class_name: FlutterGameChallengeColors
    inputs:
      - assets/colors/colors.xml

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icons/icon_android.png"
  image_path_ios: "assets/icons/icon_ios.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#4D3356"
    theme_color: "#4D3356"

flutter_native_splash:
  color: "#4D3356"
  image: assets/icons/icon_splash.png
  android_12:
    image: assets/icons/icon_splash.png
    color: "#42a5f5"
  android: true
  ios: true
  web: true
