name: flutter_game_challenge
description: A project for the Flutter game challenge.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.16.7"

dependencies:
  audioplayers: ^5.2.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flame: ^1.10.1
  flame_audio: ^2.1.3
  flame_behaviors: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.0.0
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.8
  bloc_test: ^9.1.5
  flame_test: ^1.14.0
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.5.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/

flutter_gen:
  output: lib/common/assets/

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    enabled: true
    outputs:
      class_name: FlutterGameChallengeColors
    inputs:
      - assets/colors/colors.xml
